

export enum ValidPermission {
    
    manageTours = 'manage_tours',
    createTours = 'create_tours',
    editTours = 'edit_tours',
    deleteTours = 'delete_tours',
    manageUsers = 'manage_users',
    createUsers = 'create_users',
    editUsers = 'edit_users',
    deleteUsers = 'delete_users',
    manageRoles = 'manage_roles',
    getRoles = 'get_roles',
    createRoles = 'create_roles',
    editRoles = 'edit_roles',
    deleteRoles = 'delete_roles',
    readDashboard = 'read_dashboard',
    manageBookings = 'manage_bookings',
    createBookings = 'create_bookings',
    editBookings = 'edit_bookings',
    deleteBookings = 'delete_bookings',
    manageYachts = 'manage_yachts',
    createYachts = 'create_yachts',
    editYachts = 'edit_yachts',
    deleteYachts = 'delete_yachts',
    manageClients = 'manage_clients',
    createClients = 'create_clients',
    editClients = 'edit_clients',
    deleteClients = 'delete_clients',
    manageReviews = 'manage_reviews',
    moderateReviews = 'moderate_reviews',
    manageFiles = 'manage_files',
    uploadFiles = 'upload_files',
    deleteFiles = 'delete_files',
    managePermissions = 'manage_permissions',
    manageLikes = 'manage_likes',
    manageServiceItems = 'manage_service_items',
    createServiceItems = 'create_service_items',
    editServiceItems = 'edit_service_items',
    deleteServiceItems = 'delete_service_items',
    managePayments = 'manage_payments',
    processPayments = 'process_payments',
    manageEmailQueue = 'manage_email_queue',
    manageEmailVerification = 'manage_email_verification',
    manageRedis = 'manage_redis',


}