/**
 * Tipos de notificaciones disponibles en el sistema
 * Puede expandirse según las necesidades del negocio
 */
export enum NotificationType {
  // Tickets
  TICKET_ASSIGNED = 'TICKET_ASSIGNED',
  TICKET_STATUS_CHANGED = 'TICKET_STATUS_CHANGED',
  TICKET_COMMENT = 'TICKET_COMMENT',
  TICKET_PRIORITY_CHANGED = 'TICKET_PRIORITY_CHANGED',
  TICKET_RESOLVED = 'TICKET_RESOLVED',
  TICKET_CLOSED = 'TICKET_CLOSED',

  // Mensajes
  NEW_MESSAGE = 'NEW_MESSAGE',
  MESSAGE_REPLY = 'MESSAGE_REPLY',

  // Sistema
  SYSTEM_ALERT = 'SYSTEM_ALERT',
  SYSTEM_MAINTENANCE = 'SYSTEM_MAINTENANCE',
  SYSTEM_UPDATE = 'SYSTEM_UPDATE',

  // Usuario
  USER_MENTION = 'USER_MENTION',
  USER_INVITATION = 'USER_INVITATION',
  USER_CREATED = 'USER_CREATED',

  // Enterprise
  ENTERPRISE_VERIFICATION = 'ENTERPRISE_VERIFICATION',
  ENTERPRISE_CONFIG_UPDATED = 'ENTERPRISE_CONFIG_UPDATED',

  // General
  GENERAL = 'GENERAL',
  INFO = 'INFO',
  WARNING = 'WARNING',
  ERROR = 'ERROR',
  SUCCESS = 'SUCCESS',
}
